FROM golang:latest AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o stckrslap .

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/stckrslap .
COPY --from=builder /app/static ./static

EXPOSE 10014

ENV PORT=10014
ENV INVITE_KEY=""

ENTRYPOINT ["./stckrslap"]
